---

- name: Install Grafana
  package:
    name: "{{ grafana_package }}"
    state: "{{ (grafana_version == 'latest') | ternary('latest', 'present') }}"
  register: _install_packages
  until: _install_packages is succeeded
  retries: 5
  delay: 2
